/*
 * JS for Home generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'e38e83fd-ff65-46de-b6f7-2c3ed1f302c6';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "oct10",
    "location": "oct10.html"
}, {
    "name": "IntroDigital",
    "location": "IntroDigital.html"
}, {
    "name": "mainscreen",
    "location": "mainscreen.html"
}, {
    "name": "oct13",
    "location": "oct13.html"
}];

function Home_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_6': 'Home_mobilenavbar_6',
        'home_item': 'Home_home_item',
        'products_item': 'Home_products_item',
        'account_item': 'Home_account_item',
        'mobilelabel_11': 'Home_mobilelabel_11',
        'mobileimage_25': 'Home_mobileimage_25',
        'mobilecollapsibleset_15': 'Home_mobilecollapsibleset_15',
        'mobilecollapsblock_16': 'Home_mobilecollapsblock_16',
        'mobilecollapsblockheader_17': 'Home_mobilecollapsblockheader_17',
        'mobilecollapsblockcontent_18': 'Home_mobilecollapsblockcontent_18',
        'mobilecollapsblock_26': 'Home_mobilecollapsblock_26',
        'mobilecollapsblockheader_27': 'Home_mobilecollapsblockheader_27',
        'mobilecollapsblockcontent_28': 'Home_mobilecollapsblockcontent_28',
        'googlemap_29': 'Home_googlemap_29',
        'marker_30': 'Home_marker_30',
        'collapsedblock_43': 'Home_collapsedblock_43',
        'collapsedblock_43_mobilecollapsblock_31': 'Home_collapsedblock_43_mobilecollapsblock_31',
        'collapsedblock_43_mobilecollapsblockheader_32': 'Home_collapsedblock_43_mobilecollapsblockheader_32',
        'collapsedblock_43_mobilecollapsblockcontent_33': 'Home_collapsedblock_43_mobilecollapsblockcontent_33',
        'collapsedblock_43_mobilegrid_34': 'Home_collapsedblock_43_mobilegrid_34',
        'collapsedblock_43_mobilegridcell_35': 'Home_collapsedblock_43_mobilegridcell_35',
        'collapsedblock_43_mobilelabel_39': 'Home_collapsedblock_43_mobilelabel_39',
        'collapsedblock_43_mobilegridcell_36': 'Home_collapsedblock_43_mobilegridcell_36',
        'collapsedblock_43_mobilelabel_41': 'Home_collapsedblock_43_mobilelabel_41',
        'collapsedblock_43_mobilegridcell_37': 'Home_collapsedblock_43_mobilegridcell_37',
        'collapsedblock_43_mobilelabel_40': 'Home_collapsedblock_43_mobilelabel_40',
        'collapsedblock_43_mobilegridcell_38': 'Home_collapsedblock_43_mobilegridcell_38',
        'collapsedblock_43_mobilelabel_42': 'Home_collapsedblock_43_mobilelabel_42',
        'mobilecollapsblock_31_45': 'Home_mobilecollapsblock_31_45',
        'mobilecollapsblockheader_32_46': 'Home_mobilecollapsblockheader_32_46',
        'mobilecollapsblockcontent_33_47': 'Home_mobilecollapsblockcontent_33_47',
        'mobilegrid_34_48': 'Home_mobilegrid_34_48',
        'mobilegridcell_35_49': 'Home_mobilegridcell_35_49',
        'mobilelabel_39_50': 'Home_mobilelabel_39_50',
        'mobilegridcell_36_51': 'Home_mobilegridcell_36_51',
        'mobilelabel_41_52': 'Home_mobilelabel_41_52',
        'mobilegridcell_37_53': 'Home_mobilegridcell_37_53',
        'mobilelabel_40_54': 'Home_mobilelabel_40_54',
        'mobilegridcell_38_55': 'Home_mobilegridcell_38_55',
        'mobilelabel_42_56': 'Home_mobilelabel_42_56',
        'mobilelabel_57': 'Home_mobilelabel_57',
        'mobilecollapsblock_31_59': 'Home_mobilecollapsblock_31_59',
        'mobilecollapsblockheader_32_60': 'Home_mobilecollapsblockheader_32_60',
        'mobilecollapsblockcontent_33_61': 'Home_mobilecollapsblockcontent_33_61',
        'googlemap_71': 'Home_googlemap_71',
        'marker_72': 'Home_marker_72',
        'mobilegrid_34_62': 'Home_mobilegrid_34_62',
        'mobilegridcell_35_63': 'Home_mobilegridcell_35_63',
        'mobilelabel_39_64': 'Home_mobilelabel_39_64',
        'mobilegridcell_36_65': 'Home_mobilegridcell_36_65',
        'mobilelabel_41_66': 'Home_mobilelabel_41_66',
        'mobilegridcell_37_67': 'Home_mobilegridcell_37_67',
        'mobilelabel_40_68': 'Home_mobilelabel_40_68',
        'mobilegridcell_38_69': 'Home_mobilegridcell_38_69',
        'mobilelabel_42_70': 'Home_mobilelabel_42_70',
        'mobilecollapsblock_19': 'Home_mobilecollapsblock_19',
        'mobilecollapsblockheader_20': 'Home_mobilecollapsblockheader_20',
        'mobilecollapsblockcontent_21': 'Home_mobilecollapsblockcontent_21',
        'mobilecollapsblock_31_74': 'Home_mobilecollapsblock_31_74',
        'mobilecollapsblockheader_32_75': 'Home_mobilecollapsblockheader_32_75',
        'mobilecollapsblockcontent_33_76': 'Home_mobilecollapsblockcontent_33_76',
        'mobilecollapsblock_31_87': 'Home_mobilecollapsblock_31_87',
        'mobilecollapsblockheader_32_88': 'Home_mobilecollapsblockheader_32_88',
        'mobilecollapsblockcontent_33_89': 'Home_mobilecollapsblockcontent_33_89',
        'mobilegrid_34_90': 'Home_mobilegrid_34_90',
        'mobilegridcell_35_91': 'Home_mobilegridcell_35_91',
        'mobilelabel_39_92': 'Home_mobilelabel_39_92',
        'mobilegridcell_36_93': 'Home_mobilegridcell_36_93',
        'mobilelabel_41_94': 'Home_mobilelabel_41_94',
        'mobilegridcell_37_95': 'Home_mobilegridcell_37_95',
        'mobilelabel_40_96': 'Home_mobilelabel_40_96',
        'mobilegridcell_38_97': 'Home_mobilegridcell_38_97',
        'mobilelabel_42_98': 'Home_mobilelabel_42_98',
        'mobilecollapsblock_31_100': 'Home_mobilecollapsblock_31_100',
        'mobilecollapsblockheader_32_101': 'Home_mobilecollapsblockheader_32_101',
        'mobilecollapsblockcontent_33_102': 'Home_mobilecollapsblockcontent_33_102',
        'mobilegrid_34_103': 'Home_mobilegrid_34_103',
        'mobilegridcell_35_104': 'Home_mobilegridcell_35_104',
        'mobilelabel_39_105': 'Home_mobilelabel_39_105',
        'mobilegridcell_36_106': 'Home_mobilegridcell_36_106',
        'mobilelabel_41_107': 'Home_mobilelabel_41_107',
        'mobilegridcell_37_108': 'Home_mobilegridcell_37_108',
        'mobilelabel_40_109': 'Home_mobilelabel_40_109',
        'mobilegridcell_38_110': 'Home_mobilegridcell_38_110',
        'mobilelabel_42_111': 'Home_mobilelabel_42_111',
        'mobilelabel_112': 'Home_mobilelabel_112',
        'mobilecollapsblock_22': 'Home_mobilecollapsblock_22',
        'mobilecollapsblockheader_23': 'Home_mobilecollapsblockheader_23',
        'mobilecollapsblockcontent_24': 'Home_mobilecollapsblockcontent_24',
        'mobilecollapsblock_31_114': 'Home_mobilecollapsblock_31_114',
        'mobilecollapsblockheader_32_115': 'Home_mobilecollapsblockheader_32_115',
        'mobilecollapsblockcontent_33_116': 'Home_mobilecollapsblockcontent_33_116',
        'mobilegrid_34_117': 'Home_mobilegrid_34_117',
        'mobilegridcell_35_118': 'Home_mobilegridcell_35_118',
        'mobilelabel_39_119': 'Home_mobilelabel_39_119',
        'mobilegridcell_36_120': 'Home_mobilegridcell_36_120',
        'mobilelabel_41_121': 'Home_mobilelabel_41_121',
        'mobilegridcell_37_122': 'Home_mobilegridcell_37_122',
        'mobilelabel_40_123': 'Home_mobilelabel_40_123',
        'mobilegridcell_38_124': 'Home_mobilegridcell_38_124',
        'mobilelabel_42_125': 'Home_mobilelabel_42_125',
        'mobilecollapsblock_31_130': 'Home_mobilecollapsblock_31_130',
        'mobilecollapsblockheader_32_131': 'Home_mobilecollapsblockheader_32_131',
        'mobilecollapsblockcontent_33_132': 'Home_mobilecollapsblockcontent_33_132',
        'mobilegrid_34_133': 'Home_mobilegrid_34_133',
        'mobilegridcell_35_134': 'Home_mobilegridcell_35_134',
        'mobilelabel_39_135': 'Home_mobilelabel_39_135',
        'mobilegridcell_36_136': 'Home_mobilegridcell_36_136',
        'mobilelabel_41_137': 'Home_mobilelabel_41_137',
        'mobilegridcell_37_138': 'Home_mobilegridcell_37_138',
        'mobilelabel_40_139': 'Home_mobilelabel_40_139',
        'mobilegridcell_38_140': 'Home_mobilegridcell_38_140',
        'mobilelabel_42_141': 'Home_mobilelabel_42_141',
        'mobilecollapsblock_31_143': 'Home_mobilecollapsblock_31_143',
        'mobilecollapsblockheader_32_144': 'Home_mobilecollapsblockheader_32_144',
        'mobilecollapsblockcontent_33_145': 'Home_mobilecollapsblockcontent_33_145',
        'googlemap_155': 'Home_googlemap_155',
        'marker_156': 'Home_marker_156'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Home';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Home_onLoad = function() {
            Home_elementsExtraJS();

            Home_deviceEvents();
            Home_windowEvents();
            Home_elementsEvents();
        };

    // screen window events


    function Home_windowEvents() {

        $('#Home').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Home_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Home_elementsExtraJS() {
        // screen (Home) extra code

        /* mobilecollapsblock_16 */

        $("#Home_mobilecollapsblock_16 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_26 */

        $("#Home_mobilecollapsblock_26 .ui-collapsible-heading-toggle").attr("tabindex", "2");

        /* googlemap_29 */

        $("[name = 'googlemap_29']").wrap("<div/>");
        $("[name = 'googlemap_29']").parent().css("margin-left", $("[name = 'googlemap_29']").css("margin-left"));
        $("[name = 'googlemap_29']").parent().css("margin-right", $("[name = 'googlemap_29']").css("margin-right"));
        $("[name = 'googlemap_29']").css("margin-left", '0');
        $("[name = 'googlemap_29']").css("margin-right", '0');

        var googlemap_29_options = {
            markerSourceName: "googlemap_29_markers",
            latitude: "19.23",
            longitude: "72.95",
            address: "Yantra Park Thane",
            zoom: 10,
            showLocationMarker: true
        }

        Apperyio.__registerComponent('googlemap_29', new Apperyio.ApperyMapComponent("googlemap_29", googlemap_29_options));
        $("[name='googlemap_29_markers'] [apperytype='marker']").attr("reRender", "googlemap_29");

        function __update_googlemap_29(event, ui) {
            if (($('#Home_googlemap_29', ui.toPage).length > 0) && (Apperyio('googlemap_29') != undefined) && (Apperyio('googlemap_29').isInitialized)) {
                Apperyio('googlemap_29').refresh();
            }
        }
        $(":mobile-pagecontainer").off("pagecontainershow.Home_mobilecontainer1", __update_googlemap_29).on("pagecontainershow.Home_mobilecontainer1", __update_googlemap_29);

        /* collapsedblock_43_mobilecollapsblock_31 */

        $("#Home_collapsedblock_43_mobilecollapsblock_31 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_45 */

        $("#Home_mobilecollapsblock_31_45 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_59 */

        $("#Home_mobilecollapsblock_31_59 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* googlemap_71 */

        $("[name = 'googlemap_71']").wrap("<div/>");
        $("[name = 'googlemap_71']").parent().css("margin-left", $("[name = 'googlemap_71']").css("margin-left"));
        $("[name = 'googlemap_71']").parent().css("margin-right", $("[name = 'googlemap_71']").css("margin-right"));
        $("[name = 'googlemap_71']").css("margin-left", '0');
        $("[name = 'googlemap_71']").css("margin-right", '0');

        var googlemap_71_options = {
            markerSourceName: "googlemap_71_markers",
            latitude: "19.21",
            longitude: "72.97",
            address: "Dharma,Yanta Park",
            zoom: 40,
            showLocationMarker: true
        }

        Apperyio.__registerComponent('googlemap_71', new Apperyio.ApperyMapComponent("googlemap_71", googlemap_71_options));
        $("[name='googlemap_71_markers'] [apperytype='marker']").attr("reRender", "googlemap_71");

        function __update_googlemap_71(event, ui) {
            if (($('#Home_googlemap_71', ui.toPage).length > 0) && (Apperyio('googlemap_71') != undefined) && (Apperyio('googlemap_71').isInitialized)) {
                Apperyio('googlemap_71').refresh();
            }
        }
        $(":mobile-pagecontainer").off("pagecontainershow.Home_mobilecontainer1", __update_googlemap_71).on("pagecontainershow.Home_mobilecontainer1", __update_googlemap_71);

        /* mobilecollapsblock_19 */

        $("#Home_mobilecollapsblock_19 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_31_74 */

        $("#Home_mobilecollapsblock_31_74 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_87 */

        $("#Home_mobilecollapsblock_31_87 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_100 */

        $("#Home_mobilecollapsblock_31_100 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_22 */

        $("#Home_mobilecollapsblock_22 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_31_114 */

        $("#Home_mobilecollapsblock_31_114 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_130 */

        $("#Home_mobilecollapsblock_31_130 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_143 */

        $("#Home_mobilecollapsblock_31_143 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* googlemap_155 */

        $("[name = 'googlemap_155']").wrap("<div/>");
        $("[name = 'googlemap_155']").parent().css("margin-left", $("[name = 'googlemap_155']").css("margin-left"));
        $("[name = 'googlemap_155']").parent().css("margin-right", $("[name = 'googlemap_155']").css("margin-right"));
        $("[name = 'googlemap_155']").css("margin-left", '0');
        $("[name = 'googlemap_155']").css("margin-right", '0');

        var googlemap_155_options = {
            markerSourceName: "googlemap_155_markers",
            latitude: "19.109339",
            longitude: "72.865118",
            address: "Hotel Leela",
            zoom: 30,
            showLocationMarker: true
        }

        Apperyio.__registerComponent('googlemap_155', new Apperyio.ApperyMapComponent("googlemap_155", googlemap_155_options));
        $("[name='googlemap_155_markers'] [apperytype='marker']").attr("reRender", "googlemap_155");

        function __update_googlemap_155(event, ui) {
            if (($('#Home_googlemap_155', ui.toPage).length > 0) && (Apperyio('googlemap_155') != undefined) && (Apperyio('googlemap_155').isInitialized)) {
                Apperyio('googlemap_155').refresh();
            }
        }
        $(":mobile-pagecontainer").off("pagecontainershow.Home_mobilecontainer1", __update_googlemap_155).on("pagecontainershow.Home_mobilecontainer1", __update_googlemap_155);

    };

    // screen elements handler


    function Home_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Home_mobileheader1 [name="home_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#Home_mobileheader1 [name="home_item"]');
        $(document).off("click", '#Home_mobileheader1 [name="products_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('oct10', {
                        reverse: false
                    });

                }
            },
        }, '#Home_mobileheader1 [name="products_item"]');
        $(document).off("click", '#Home_mobileheader1 [name="account_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('oct13', {
                        reverse: false
                    });

                }
            },
        }, '#Home_mobileheader1 [name="account_item"]');

        $(document).off("click", '#Home_mobilecontainer1 [name="mobilelabel_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://en.wikipedia.org/wiki/Mumbai', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');

                }
            },
        }, '#Home_mobilecontainer1 [name="mobilelabel_11"]');

    };

    $(document).off("pagebeforeshow", "#Home").on("pagebeforeshow", "#Home", function(event, ui) {
        Apperyio.CurrentScreen = "Home";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Home_onLoad();
};

$(document).off("pagecreate", "#Home").on("pagecreate", "#Home", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Home_js();
});