/*
 * JS for IntroDigital generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'e38e83fd-ff65-46de-b6f7-2c3ed1f302c6';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "oct10",
    "location": "oct10.html"
}, {
    "name": "IntroDigital",
    "location": "IntroDigital.html"
}, {
    "name": "mainscreen",
    "location": "mainscreen.html"
}, {
    "name": "oct13",
    "location": "oct13.html"
}];

function IntroDigital_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilegrid_4': 'IntroDigital_mobilegrid_4',
        'mobilegridcell_5': 'IntroDigital_mobilegridcell_5',
        'mobileimage_2': 'IntroDigital_mobileimage_2',
        'mobilegridcell_6': 'IntroDigital_mobilegridcell_6',
        'spacer_10': 'IntroDigital_spacer_10',
        'mobilelabel_3': 'IntroDigital_mobilelabel_3',
        'mobilelabel_11': 'IntroDigital_mobilelabel_11',
        'mobilelabel_14': 'IntroDigital_mobilelabel_14',
        'mobilelabel_12': 'IntroDigital_mobilelabel_12',
        'mobilelabel_13': 'IntroDigital_mobilelabel_13',
        'spacer_23': 'IntroDigital_spacer_23',
        'mobilegrid_15': 'IntroDigital_mobilegrid_15',
        'mobilegridcell_16': 'IntroDigital_mobilegridcell_16',
        'mobileimage_20': 'IntroDigital_mobileimage_20',
        'mobilegridcell_17': 'IntroDigital_mobilegridcell_17',
        'spacer_22': 'IntroDigital_spacer_22',
        'mobilelabel_21': 'IntroDigital_mobilelabel_21',
        'mobilelabel_24': 'IntroDigital_mobilelabel_24',
        'mobilelabel_25': 'IntroDigital_mobilelabel_25',
        'mobilelabel_26': 'IntroDigital_mobilelabel_26',
        'mobilelabel_27': 'IntroDigital_mobilelabel_27'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'IntroDigital';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var IntroDigital_onLoad = function() {
            IntroDigital_elementsExtraJS();

            IntroDigital_deviceEvents();
            IntroDigital_windowEvents();
            IntroDigital_elementsEvents();
        };

    // screen window events


    function IntroDigital_windowEvents() {

        $('#IntroDigital').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function IntroDigital_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function IntroDigital_elementsExtraJS() {
        // screen (IntroDigital) extra code

    };

    // screen elements handler


    function IntroDigital_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

    };

    $(document).off("pagebeforeshow", "#IntroDigital").on("pagebeforeshow", "#IntroDigital", function(event, ui) {
        Apperyio.CurrentScreen = "IntroDigital";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    IntroDigital_onLoad();
};

$(document).off("pagecreate", "#IntroDigital").on("pagecreate", "#IntroDigital", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    IntroDigital_js();
});