/*
 * JS for mainscreen generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'e38e83fd-ff65-46de-b6f7-2c3ed1f302c6';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "oct10",
    "location": "oct10.html"
}, {
    "name": "IntroDigital",
    "location": "IntroDigital.html"
}, {
    "name": "mainscreen",
    "location": "mainscreen.html"
}, {
    "name": "oct13",
    "location": "oct13.html"
}];

function mainscreen_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'spacer_3': 'mainscreen_spacer_3',
        'mobileimage_2': 'mainscreen_mobileimage_2',
        'spacer_6': 'mainscreen_spacer_6',
        'mobilebutton_7': 'mainscreen_mobilebutton_7'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'mainscreen';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var mainscreen_onLoad = function() {
            mainscreen_elementsExtraJS();

            mainscreen_deviceEvents();
            mainscreen_windowEvents();
            mainscreen_elementsEvents();
        };

    // screen window events


    function mainscreen_windowEvents() {

        $('#mainscreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function mainscreen_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function mainscreen_elementsExtraJS() {
        // screen (mainscreen) extra code

    };

    // screen elements handler


    function mainscreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#mainscreen_mobilecontainer [name="mobilebutton_7"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#mainscreen_mobilecontainer [name="mobilebutton_7"]');

    };

    $(document).off("pagebeforeshow", "#mainscreen").on("pagebeforeshow", "#mainscreen", function(event, ui) {
        Apperyio.CurrentScreen = "mainscreen";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    mainscreen_onLoad();
};

$(document).off("pagecreate", "#mainscreen").on("pagecreate", "#mainscreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    mainscreen_js();
});