/*
 * JS for oct13 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'e38e83fd-ff65-46de-b6f7-2c3ed1f302c6';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "oct10",
    "location": "oct10.html"
}, {
    "name": "IntroDigital",
    "location": "IntroDigital.html"
}, {
    "name": "mainscreen",
    "location": "mainscreen.html"
}, {
    "name": "oct13",
    "location": "oct13.html"
}];

function oct13_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_6': 'oct13_mobilenavbar_6',
        'home_item': 'oct13_home_item',
        'products_item': 'oct13_products_item',
        'account_item': 'oct13_account_item',
        'mobilelabel_11': 'oct13_mobilelabel_11',
        'mobileimage_25': 'oct13_mobileimage_25',
        'mobilecollapsibleset_15': 'oct13_mobilecollapsibleset_15',
        'mobilecollapsblock_16': 'oct13_mobilecollapsblock_16',
        'mobilecollapsblockheader_17': 'oct13_mobilecollapsblockheader_17',
        'mobilecollapsblockcontent_18': 'oct13_mobilecollapsblockcontent_18',
        'mobilecollapsblock_26': 'oct13_mobilecollapsblock_26',
        'mobilecollapsblockheader_27': 'oct13_mobilecollapsblockheader_27',
        'mobilecollapsblockcontent_28': 'oct13_mobilecollapsblockcontent_28',
        'googlemap_29': 'oct13_googlemap_29',
        'marker_30': 'oct13_marker_30',
        'mobilecollapsblock_31_157': 'oct13_mobilecollapsblock_31_157',
        'mobilecollapsblockheader_32_158': 'oct13_mobilecollapsblockheader_32_158',
        'mobilecollapsblockcontent_33_159': 'oct13_mobilecollapsblockcontent_33_159',
        'mobilegrid_34_160': 'oct13_mobilegrid_34_160',
        'mobilegridcell_35_161': 'oct13_mobilegridcell_35_161',
        'mobilelabel_39_162': 'oct13_mobilelabel_39_162',
        'mobilegridcell_36_163': 'oct13_mobilegridcell_36_163',
        'mobilelabel_41_164': 'oct13_mobilelabel_41_164',
        'mobilegridcell_37_165': 'oct13_mobilegridcell_37_165',
        'mobilelabel_40_166': 'oct13_mobilelabel_40_166',
        'mobilegridcell_38_167': 'oct13_mobilegridcell_38_167',
        'mobilelabel_42_168': 'oct13_mobilelabel_42_168',
        'mobilecollapsblock_31_45': 'oct13_mobilecollapsblock_31_45',
        'mobilecollapsblockheader_32_46': 'oct13_mobilecollapsblockheader_32_46',
        'mobilecollapsblockcontent_33_47': 'oct13_mobilecollapsblockcontent_33_47',
        'mobilegrid_34_48': 'oct13_mobilegrid_34_48',
        'mobilegridcell_35_49': 'oct13_mobilegridcell_35_49',
        'mobilelabel_39_50': 'oct13_mobilelabel_39_50',
        'mobilegridcell_36_51': 'oct13_mobilegridcell_36_51',
        'mobilelabel_41_52': 'oct13_mobilelabel_41_52',
        'mobilegridcell_37_53': 'oct13_mobilegridcell_37_53',
        'mobilelabel_40_54': 'oct13_mobilelabel_40_54',
        'mobilegridcell_38_55': 'oct13_mobilegridcell_38_55',
        'mobilelabel_42_56': 'oct13_mobilelabel_42_56',
        'mobilelabel_171': 'oct13_mobilelabel_171',
        'mobilecollapsblock_31_186': 'oct13_mobilecollapsblock_31_186',
        'mobilecollapsblockheader_32_187': 'oct13_mobilecollapsblockheader_32_187',
        'mobilecollapsblockcontent_33_188': 'oct13_mobilecollapsblockcontent_33_188',
        'mobilegrid_34_189': 'oct13_mobilegrid_34_189',
        'mobilegridcell_35_190': 'oct13_mobilegridcell_35_190',
        'mobilelabel_39_191': 'oct13_mobilelabel_39_191',
        'mobilegridcell_36_192': 'oct13_mobilegridcell_36_192',
        'mobilelabel_41_193': 'oct13_mobilelabel_41_193',
        'mobilegridcell_37_194': 'oct13_mobilegridcell_37_194',
        'mobilelabel_40_195': 'oct13_mobilelabel_40_195',
        'mobilegridcell_38_196': 'oct13_mobilegridcell_38_196',
        'mobilelabel_42_197': 'oct13_mobilelabel_42_197',
        'mobilecollapsblock_31_199': 'oct13_mobilecollapsblock_31_199',
        'mobilecollapsblockheader_32_200': 'oct13_mobilecollapsblockheader_32_200',
        'mobilecollapsblockcontent_33_201': 'oct13_mobilecollapsblockcontent_33_201',
        'mobilegrid_34_202': 'oct13_mobilegrid_34_202',
        'mobilegridcell_35_203': 'oct13_mobilegridcell_35_203',
        'mobilelabel_39_204': 'oct13_mobilelabel_39_204',
        'mobilegridcell_36_205': 'oct13_mobilegridcell_36_205',
        'mobilelabel_41_206': 'oct13_mobilelabel_41_206',
        'mobilegridcell_37_207': 'oct13_mobilegridcell_37_207',
        'mobilelabel_40_208': 'oct13_mobilelabel_40_208',
        'mobilegridcell_38_209': 'oct13_mobilegridcell_38_209',
        'mobilelabel_42_210': 'oct13_mobilelabel_42_210',
        'mobilelabel_211': 'oct13_mobilelabel_211',
        'mobilecollapsblock_19': 'oct13_mobilecollapsblock_19',
        'mobilecollapsblockheader_20': 'oct13_mobilecollapsblockheader_20',
        'mobilecollapsblockcontent_21': 'oct13_mobilecollapsblockcontent_21',
        'mobilecollapsblock_31_87': 'oct13_mobilecollapsblock_31_87',
        'mobilecollapsblockheader_32_88': 'oct13_mobilecollapsblockheader_32_88',
        'mobilecollapsblockcontent_33_89': 'oct13_mobilecollapsblockcontent_33_89',
        'mobilegrid_34_90': 'oct13_mobilegrid_34_90',
        'mobilegridcell_35_91': 'oct13_mobilegridcell_35_91',
        'mobilelabel_39_92': 'oct13_mobilelabel_39_92',
        'mobilegridcell_36_93': 'oct13_mobilegridcell_36_93',
        'mobilelabel_41_94': 'oct13_mobilelabel_41_94',
        'mobilegridcell_37_95': 'oct13_mobilegridcell_37_95',
        'mobilelabel_40_96': 'oct13_mobilelabel_40_96',
        'mobilegridcell_38_97': 'oct13_mobilegridcell_38_97',
        'mobilelabel_42_98': 'oct13_mobilelabel_42_98',
        'mobilelabel_212': 'oct13_mobilelabel_212',
        'mobilecollapsblock_31_100': 'oct13_mobilecollapsblock_31_100',
        'mobilecollapsblockheader_32_101': 'oct13_mobilecollapsblockheader_32_101',
        'mobilecollapsblockcontent_33_102': 'oct13_mobilecollapsblockcontent_33_102',
        'mobilegrid_34_103': 'oct13_mobilegrid_34_103',
        'mobilegridcell_35_104': 'oct13_mobilegridcell_35_104',
        'mobilelabel_39_105': 'oct13_mobilelabel_39_105',
        'mobilegridcell_36_106': 'oct13_mobilegridcell_36_106',
        'mobilelabel_41_107': 'oct13_mobilelabel_41_107',
        'mobilegridcell_37_108': 'oct13_mobilegridcell_37_108',
        'mobilelabel_40_109': 'oct13_mobilelabel_40_109',
        'mobilegridcell_38_110': 'oct13_mobilegridcell_38_110',
        'mobilelabel_42_111': 'oct13_mobilelabel_42_111',
        'mobilecollapsblock_22': 'oct13_mobilecollapsblock_22',
        'mobilecollapsblockheader_23': 'oct13_mobilecollapsblockheader_23',
        'mobilecollapsblockcontent_24': 'oct13_mobilecollapsblockcontent_24',
        'mobilecollapsblock_31_173': 'oct13_mobilecollapsblock_31_173',
        'mobilecollapsblockheader_32_174': 'oct13_mobilecollapsblockheader_32_174',
        'mobilecollapsblockcontent_33_175': 'oct13_mobilecollapsblockcontent_33_175',
        'mobilegrid_34_176': 'oct13_mobilegrid_34_176',
        'mobilegridcell_35_177': 'oct13_mobilegridcell_35_177',
        'mobilelabel_39_178': 'oct13_mobilelabel_39_178',
        'mobilegridcell_36_179': 'oct13_mobilegridcell_36_179',
        'mobilelabel_41_180': 'oct13_mobilelabel_41_180',
        'mobilegridcell_37_181': 'oct13_mobilegridcell_37_181',
        'mobilelabel_40_182': 'oct13_mobilelabel_40_182',
        'mobilegridcell_38_183': 'oct13_mobilegridcell_38_183',
        'mobilelabel_42_184': 'oct13_mobilelabel_42_184',
        'mobilecollapsblock_31_143': 'oct13_mobilecollapsblock_31_143',
        'mobilecollapsblockheader_32_144': 'oct13_mobilecollapsblockheader_32_144',
        'mobilecollapsblockcontent_33_145': 'oct13_mobilecollapsblockcontent_33_145'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'oct13';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var oct13_onLoad = function() {
            oct13_elementsExtraJS();

            oct13_deviceEvents();
            oct13_windowEvents();
            oct13_elementsEvents();
        };

    // screen window events


    function oct13_windowEvents() {

        $('#oct13').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function oct13_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function oct13_elementsExtraJS() {
        // screen (oct13) extra code

        /* mobilecollapsblock_16 */

        $("#oct13_mobilecollapsblock_16 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_26 */

        $("#oct13_mobilecollapsblock_26 .ui-collapsible-heading-toggle").attr("tabindex", "2");

        /* googlemap_29 */

        $("[name = 'googlemap_29']").wrap("<div/>");
        $("[name = 'googlemap_29']").parent().css("margin-left", $("[name = 'googlemap_29']").css("margin-left"));
        $("[name = 'googlemap_29']").parent().css("margin-right", $("[name = 'googlemap_29']").css("margin-right"));
        $("[name = 'googlemap_29']").css("margin-left", '0');
        $("[name = 'googlemap_29']").css("margin-right", '0');

        var googlemap_29_options = {
            markerSourceName: "googlemap_29_markers",
            latitude: "12.985262",
            longitude: "77.741231",
            address: "GR TechPark",
            zoom: 10,
            showLocationMarker: true
        }

        Apperyio.__registerComponent('googlemap_29', new Apperyio.ApperyMapComponent("googlemap_29", googlemap_29_options));
        $("[name='googlemap_29_markers'] [apperytype='marker']").attr("reRender", "googlemap_29");

        function __update_googlemap_29(event, ui) {
            if (($('#oct13_googlemap_29', ui.toPage).length > 0) && (Apperyio('googlemap_29') != undefined) && (Apperyio('googlemap_29').isInitialized)) {
                Apperyio('googlemap_29').refresh();
            }
        }
        $(":mobile-pagecontainer").off("pagecontainershow.oct13_mobilecontainer1", __update_googlemap_29).on("pagecontainershow.oct13_mobilecontainer1", __update_googlemap_29);

        /* mobilecollapsblock_31_157 */

        $("#oct13_mobilecollapsblock_31_157 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_45 */

        $("#oct13_mobilecollapsblock_31_45 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_186 */

        $("#oct13_mobilecollapsblock_31_186 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_199 */

        $("#oct13_mobilecollapsblock_31_199 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_19 */

        $("#oct13_mobilecollapsblock_19 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_31_87 */

        $("#oct13_mobilecollapsblock_31_87 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_100 */

        $("#oct13_mobilecollapsblock_31_100 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_22 */

        $("#oct13_mobilecollapsblock_22 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_31_173 */

        $("#oct13_mobilecollapsblock_31_173 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_143 */

        $("#oct13_mobilecollapsblock_31_143 .ui-collapsible-heading-toggle").attr("tabindex", "4");

    };

    // screen elements handler


    function oct13_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#oct13_mobileheader1 [name="home_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('oct13', {
                        reverse: false
                    });
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#oct13_mobileheader1 [name="home_item"]');
        $(document).off("click", '#oct13_mobileheader1 [name="products_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('oct10', {
                        reverse: false
                    });

                }
            },
        }, '#oct13_mobileheader1 [name="products_item"]');

        $(document).off("click", '#oct13_mobilecontainer1 [name="mobilelabel_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://en.wikipedia.org/wiki/Bangalore', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');

                }
            },
        }, '#oct13_mobilecontainer1 [name="mobilelabel_11"]');

    };

    $(document).off("pagebeforeshow", "#oct13").on("pagebeforeshow", "#oct13", function(event, ui) {
        Apperyio.CurrentScreen = "oct13";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    oct13_onLoad();
};

$(document).off("pagecreate", "#oct13").on("pagecreate", "#oct13", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    oct13_js();
});