/*
 * JS for oct10 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'e38e83fd-ff65-46de-b6f7-2c3ed1f302c6';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "oct10",
    "location": "oct10.html"
}, {
    "name": "IntroDigital",
    "location": "IntroDigital.html"
}, {
    "name": "mainscreen",
    "location": "mainscreen.html"
}, {
    "name": "oct13",
    "location": "oct13.html"
}];

function oct10_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilenavbar_6': 'oct10_mobilenavbar_6',
        'home_item': 'oct10_home_item',
        'products_item': 'oct10_products_item',
        'account_item': 'oct10_account_item',
        'mobilelabel_11': 'oct10_mobilelabel_11',
        'mobileimage_25': 'oct10_mobileimage_25',
        'mobilecollapsibleset_15': 'oct10_mobilecollapsibleset_15',
        'mobilecollapsblock_16': 'oct10_mobilecollapsblock_16',
        'mobilecollapsblockheader_17': 'oct10_mobilecollapsblockheader_17',
        'mobilecollapsblockcontent_18': 'oct10_mobilecollapsblockcontent_18',
        'mobilecollapsblock_26': 'oct10_mobilecollapsblock_26',
        'mobilecollapsblockheader_27': 'oct10_mobilecollapsblockheader_27',
        'mobilecollapsblockcontent_28': 'oct10_mobilecollapsblockcontent_28',
        'googlemap_29': 'oct10_googlemap_29',
        'marker_30': 'oct10_marker_30',
        'mobilecollapsblock_31_157': 'oct10_mobilecollapsblock_31_157',
        'mobilecollapsblockheader_32_158': 'oct10_mobilecollapsblockheader_32_158',
        'mobilecollapsblockcontent_33_159': 'oct10_mobilecollapsblockcontent_33_159',
        'mobilegrid_34_160': 'oct10_mobilegrid_34_160',
        'mobilegridcell_35_161': 'oct10_mobilegridcell_35_161',
        'mobilelabel_39_162': 'oct10_mobilelabel_39_162',
        'mobilegridcell_36_163': 'oct10_mobilegridcell_36_163',
        'mobilelabel_41_164': 'oct10_mobilelabel_41_164',
        'mobilegridcell_37_165': 'oct10_mobilegridcell_37_165',
        'mobilelabel_40_166': 'oct10_mobilelabel_40_166',
        'mobilegridcell_38_167': 'oct10_mobilegridcell_38_167',
        'mobilelabel_42_168': 'oct10_mobilelabel_42_168',
        'mobilelabel_170': 'oct10_mobilelabel_170',
        'mobilelabel_57': 'oct10_mobilelabel_57',
        'mobilecollapsblock_31_45': 'oct10_mobilecollapsblock_31_45',
        'mobilecollapsblockheader_32_46': 'oct10_mobilecollapsblockheader_32_46',
        'mobilecollapsblockcontent_33_47': 'oct10_mobilecollapsblockcontent_33_47',
        'mobilegrid_34_48': 'oct10_mobilegrid_34_48',
        'mobilegridcell_35_49': 'oct10_mobilegridcell_35_49',
        'mobilelabel_39_50': 'oct10_mobilelabel_39_50',
        'mobilegridcell_36_51': 'oct10_mobilegridcell_36_51',
        'mobilelabel_41_52': 'oct10_mobilelabel_41_52',
        'mobilegridcell_37_53': 'oct10_mobilegridcell_37_53',
        'mobilelabel_40_54': 'oct10_mobilelabel_40_54',
        'mobilegridcell_38_55': 'oct10_mobilegridcell_38_55',
        'mobilelabel_42_56': 'oct10_mobilelabel_42_56',
        'mobilelabel_171': 'oct10_mobilelabel_171',
        'mobilecollapsblock_19': 'oct10_mobilecollapsblock_19',
        'mobilecollapsblockheader_20': 'oct10_mobilecollapsblockheader_20',
        'mobilecollapsblockcontent_21': 'oct10_mobilecollapsblockcontent_21',
        'mobilecollapsblock_31_87': 'oct10_mobilecollapsblock_31_87',
        'mobilecollapsblockheader_32_88': 'oct10_mobilecollapsblockheader_32_88',
        'mobilecollapsblockcontent_33_89': 'oct10_mobilecollapsblockcontent_33_89',
        'mobilegrid_34_90': 'oct10_mobilegrid_34_90',
        'mobilegridcell_35_91': 'oct10_mobilegridcell_35_91',
        'mobilelabel_39_92': 'oct10_mobilelabel_39_92',
        'mobilegridcell_36_93': 'oct10_mobilegridcell_36_93',
        'mobilelabel_41_94': 'oct10_mobilelabel_41_94',
        'mobilegridcell_37_95': 'oct10_mobilegridcell_37_95',
        'mobilelabel_40_96': 'oct10_mobilelabel_40_96',
        'mobilegridcell_38_97': 'oct10_mobilegridcell_38_97',
        'mobilelabel_42_98': 'oct10_mobilelabel_42_98',
        'mobilecollapsblock_31_100': 'oct10_mobilecollapsblock_31_100',
        'mobilecollapsblockheader_32_101': 'oct10_mobilecollapsblockheader_32_101',
        'mobilecollapsblockcontent_33_102': 'oct10_mobilecollapsblockcontent_33_102',
        'mobilegrid_34_103': 'oct10_mobilegrid_34_103',
        'mobilegridcell_35_104': 'oct10_mobilegridcell_35_104',
        'mobilelabel_39_105': 'oct10_mobilelabel_39_105',
        'mobilegridcell_36_106': 'oct10_mobilegridcell_36_106',
        'mobilelabel_41_107': 'oct10_mobilelabel_41_107',
        'mobilegridcell_37_108': 'oct10_mobilegridcell_37_108',
        'mobilelabel_40_109': 'oct10_mobilelabel_40_109',
        'mobilegridcell_38_110': 'oct10_mobilegridcell_38_110',
        'mobilelabel_42_111': 'oct10_mobilelabel_42_111',
        'mobilelabel_112': 'oct10_mobilelabel_112',
        'mobilecollapsblock_22': 'oct10_mobilecollapsblock_22',
        'mobilecollapsblockheader_23': 'oct10_mobilecollapsblockheader_23',
        'mobilecollapsblockcontent_24': 'oct10_mobilecollapsblockcontent_24',
        'mobilecollapsblock_31_114': 'oct10_mobilecollapsblock_31_114',
        'mobilecollapsblockheader_32_115': 'oct10_mobilecollapsblockheader_32_115',
        'mobilecollapsblockcontent_33_116': 'oct10_mobilecollapsblockcontent_33_116',
        'mobilegrid_34_117': 'oct10_mobilegrid_34_117',
        'mobilegridcell_35_118': 'oct10_mobilegridcell_35_118',
        'mobilelabel_39_119': 'oct10_mobilelabel_39_119',
        'mobilegridcell_36_120': 'oct10_mobilegridcell_36_120',
        'mobilelabel_41_121': 'oct10_mobilelabel_41_121',
        'mobilegridcell_37_122': 'oct10_mobilegridcell_37_122',
        'mobilelabel_40_123': 'oct10_mobilelabel_40_123',
        'mobilegridcell_38_124': 'oct10_mobilegridcell_38_124',
        'mobilelabel_42_125': 'oct10_mobilelabel_42_125',
        'mobilecollapsblock_31_130': 'oct10_mobilecollapsblock_31_130',
        'mobilecollapsblockheader_32_131': 'oct10_mobilecollapsblockheader_32_131',
        'mobilecollapsblockcontent_33_132': 'oct10_mobilecollapsblockcontent_33_132',
        'mobilegrid_34_133': 'oct10_mobilegrid_34_133',
        'mobilegridcell_35_134': 'oct10_mobilegridcell_35_134',
        'mobilelabel_39_135': 'oct10_mobilelabel_39_135',
        'mobilegridcell_36_136': 'oct10_mobilegridcell_36_136',
        'mobilelabel_41_137': 'oct10_mobilelabel_41_137',
        'mobilegridcell_37_138': 'oct10_mobilegridcell_37_138',
        'mobilelabel_40_139': 'oct10_mobilelabel_40_139',
        'mobilegridcell_38_140': 'oct10_mobilegridcell_38_140',
        'mobilelabel_42_141': 'oct10_mobilelabel_42_141',
        'mobilecollapsblock_31_173': 'oct10_mobilecollapsblock_31_173',
        'mobilecollapsblockheader_32_174': 'oct10_mobilecollapsblockheader_32_174',
        'mobilecollapsblockcontent_33_175': 'oct10_mobilecollapsblockcontent_33_175',
        'mobilegrid_34_176': 'oct10_mobilegrid_34_176',
        'mobilegridcell_35_177': 'oct10_mobilegridcell_35_177',
        'mobilelabel_39_178': 'oct10_mobilelabel_39_178',
        'mobilegridcell_36_179': 'oct10_mobilegridcell_36_179',
        'mobilelabel_41_180': 'oct10_mobilelabel_41_180',
        'mobilegridcell_37_181': 'oct10_mobilegridcell_37_181',
        'mobilelabel_40_182': 'oct10_mobilelabel_40_182',
        'mobilegridcell_38_183': 'oct10_mobilegridcell_38_183',
        'mobilelabel_42_184': 'oct10_mobilelabel_42_184',
        'mobilecollapsblock_31_143': 'oct10_mobilecollapsblock_31_143',
        'mobilecollapsblockheader_32_144': 'oct10_mobilecollapsblockheader_32_144',
        'mobilecollapsblockcontent_33_145': 'oct10_mobilecollapsblockcontent_33_145',
        'googlemap_155': 'oct10_googlemap_155',
        'marker_156': 'oct10_marker_156'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'oct10';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var oct10_onLoad = function() {
            oct10_elementsExtraJS();

            oct10_deviceEvents();
            oct10_windowEvents();
            oct10_elementsEvents();
        };

    // screen window events


    function oct10_windowEvents() {

        $('#oct10').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function oct10_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function oct10_elementsExtraJS() {
        // screen (oct10) extra code

        /* mobilecollapsblock_16 */

        $("#oct10_mobilecollapsblock_16 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_26 */

        $("#oct10_mobilecollapsblock_26 .ui-collapsible-heading-toggle").attr("tabindex", "2");

        /* googlemap_29 */

        $("[name = 'googlemap_29']").wrap("<div/>");
        $("[name = 'googlemap_29']").parent().css("margin-left", $("[name = 'googlemap_29']").css("margin-left"));
        $("[name = 'googlemap_29']").parent().css("margin-right", $("[name = 'googlemap_29']").css("margin-right"));
        $("[name = 'googlemap_29']").css("margin-left", '0');
        $("[name = 'googlemap_29']").css("margin-right", '0');

        var googlemap_29_options = {
            markerSourceName: "googlemap_29_markers",
            latitude: "19.120602",
            longitude: "72.854878",
            address: "Banayan Park ",
            zoom: 10,
            showLocationMarker: true
        }

        Apperyio.__registerComponent('googlemap_29', new Apperyio.ApperyMapComponent("googlemap_29", googlemap_29_options));
        $("[name='googlemap_29_markers'] [apperytype='marker']").attr("reRender", "googlemap_29");

        function __update_googlemap_29(event, ui) {
            if (($('#oct10_googlemap_29', ui.toPage).length > 0) && (Apperyio('googlemap_29') != undefined) && (Apperyio('googlemap_29').isInitialized)) {
                Apperyio('googlemap_29').refresh();
            }
        }
        $(":mobile-pagecontainer").off("pagecontainershow.oct10_mobilecontainer1", __update_googlemap_29).on("pagecontainershow.oct10_mobilecontainer1", __update_googlemap_29);

        /* mobilecollapsblock_31_157 */

        $("#oct10_mobilecollapsblock_31_157 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_45 */

        $("#oct10_mobilecollapsblock_31_45 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_19 */

        $("#oct10_mobilecollapsblock_19 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_31_87 */

        $("#oct10_mobilecollapsblock_31_87 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_100 */

        $("#oct10_mobilecollapsblock_31_100 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_22 */

        $("#oct10_mobilecollapsblock_22 .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_31_114 */

        $("#oct10_mobilecollapsblock_31_114 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_130 */

        $("#oct10_mobilecollapsblock_31_130 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_173 */

        $("#oct10_mobilecollapsblock_31_173 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* mobilecollapsblock_31_143 */

        $("#oct10_mobilecollapsblock_31_143 .ui-collapsible-heading-toggle").attr("tabindex", "4");

        /* googlemap_155 */

        $("[name = 'googlemap_155']").wrap("<div/>");
        $("[name = 'googlemap_155']").parent().css("margin-left", $("[name = 'googlemap_155']").css("margin-left"));
        $("[name = 'googlemap_155']").parent().css("margin-right", $("[name = 'googlemap_155']").css("margin-right"));
        $("[name = 'googlemap_155']").css("margin-left", '0');
        $("[name = 'googlemap_155']").css("margin-right", '0');

        var googlemap_155_options = {
            markerSourceName: "googlemap_155_markers",
            latitude: "19.109339",
            longitude: "72.865118",
            address: "Hotel Leela",
            zoom: 30,
            showLocationMarker: true
        }

        Apperyio.__registerComponent('googlemap_155', new Apperyio.ApperyMapComponent("googlemap_155", googlemap_155_options));
        $("[name='googlemap_155_markers'] [apperytype='marker']").attr("reRender", "googlemap_155");

        function __update_googlemap_155(event, ui) {
            if (($('#oct10_googlemap_155', ui.toPage).length > 0) && (Apperyio('googlemap_155') != undefined) && (Apperyio('googlemap_155').isInitialized)) {
                Apperyio('googlemap_155').refresh();
            }
        }
        $(":mobile-pagecontainer").off("pagecontainershow.oct10_mobilecontainer1", __update_googlemap_155).on("pagecontainershow.oct10_mobilecontainer1", __update_googlemap_155);

    };

    // screen elements handler


    function oct10_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#oct10_mobileheader1 [name="home_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#oct10_mobileheader1 [name="home_item"]');

        $(document).off("click", '#oct10_mobileheader1 [name="account_item"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('oct13', {
                        reverse: false
                    });

                }
            },
        }, '#oct10_mobileheader1 [name="account_item"]');

        $(document).off("click", '#oct10_mobilecontainer1 [name="mobilelabel_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    window.open('https://en.wikipedia.org/wiki/Mumbai', 'NewWindow', 'width=600,height=400,toolbar=yes,location=yes,directories=yes,status=yes,menubar=yes,scrollbars=yes,copyhistory=yes,resizable=yes');

                }
            },
        }, '#oct10_mobilecontainer1 [name="mobilelabel_11"]');

        $(document).off("click", '#oct10_mobilecontainer1 [name="mobilelabel_170"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('IntroDigital', {
                        reverse: false
                    });

                }
            },
        }, '#oct10_mobilecontainer1 [name="mobilelabel_170"]');

    };

    $(document).off("pagebeforeshow", "#oct10").on("pagebeforeshow", "#oct10", function(event, ui) {
        Apperyio.CurrentScreen = "oct10";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    oct10_onLoad();
};

$(document).off("pagecreate", "#oct10").on("pagecreate", "#oct10", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    oct10_js();
});